version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "33060:33060"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: epytodo
      MYSQL_DATABASE: epytodo_db
      MYSQL_ROOT_PASSWORD: epytodo
      MYSQL_ALLOW_EMPTY_PASSWORD: epytodo
      MYSQL_RANDOM_ROOT_PASSWORD: epytodo
    volumes:
      - ./epytodo.sql:/docker-entrypoint-initdb.d/epytodo.sql
